### ISSUE TITLE
Cross platform game

### ISSUE THREAD

**Issue by rodrigoratan** [Microsoft/Windows-appsample-quizgame#1]
How hard would be to adapt it to work (share code) with Xamarin Forms? Android and iOS can also communicate in local network, but the p2pHelper part that I've seen is dependent on Windows Networking APIs, may be if it turns to a interface, it may be implemented on another platforms...

**Comment by KarlErickson** [comment]
The interfaces that you would have to implement to support other P2P APIs with the QuizGame logic are IHostCommunicator and IClientCommunicator in the Model folder of the client and host apps. These interfaces are currently implemented only by the HostCommunicator and ClientCommunicator classes, which wrap the P2PHelper APIs. You would also have to adjust the ViewModelLocator class to instantiate the HostViewModel and ClientViewModel classes by passing in instances of your custom IHostCommunicator and IClientCommunicator implementations.

**Comment by rodrigoratan** [comment]
Hi Karl! thank you for the guidance! Excelent sample app!
I see a lot of paths to evolve this, not only bringing it to xamarin cross platfom, but also other ways of implementing the multiplayer, I like the p2p 'lan mode', but this is still require a local network, may be using proximity apis to bring wifi-direct, bluetooth, for a 'real p2p mode', and may be also an online mode, because if today implementation require a local network so the chances of it being connected to internet is huge, and why not bring folks over the internet to the game? may be all ways mixed so local players that are connected to the same network can use the p2p 'lan mode' to get better performance, and people that are connected at other networks with Internet access or may be people not connected to any network but with bluetooth support can join the game if the 'host' is 'connectable' by any of this connection options and if the host is connected to internet then it can host a multiplayer multiconnections online/offline p2p.... I like the idea of implementing all this for the game but this sample also opened my mind for solutions for a cross-platform scenario that I have with a new client that requires (offline when possible) p2p communication for transactions and I was already studying the proximity apis for the windows apps and the android/ios equivalent bluetooth/wifi direct apis, now studying this sample a little more I see a lot of similarities between the two scenarios (game and my prospect client project) so I see this sample as a great playground to play with all these technologies to learn! Thank you again! I let you know if I can advance in some of the ways that I mentioned!

**Comment by KarlErickson** [comment]
Thanks, Rodrigo! Yes, there are lots of interesting ways to extend this. We wanted to demonstrate some of the easiest ways (that is, ways with the fewest external dependencies, such as web services), but we totally agree that an ideal experience would provide multiple connection options. We're thinking about implementing a few ideas, but we'd love to see where others go with it, too. Good luck!
