### ISSUE TITLE
ViewModel is never set in QuizGameClient

### ISSUE THREAD

**Issue by Hector47** [Microsoft/Windows-appsample-quizgame#2]
When executing the QuizGameClient, the ViewModel is never set resulting in a NullReferenceException in the auto-generated code behind of ClientView.xaml.

**Comment by KarlErickson** [comment]
Thanks for the report, Hector! I'll get a fix out soon.

**Comment by Hector47** [comment]
Corrected in my fork.
Anyway, nice sample, really fun to run on my TV (Raspberry Pi) and play with my phones.

**Comment by KarlErickson** [comment]
Fixed. I changed the way the view models are hooked up, using a slightly cleaner approach. Thanks again for the report. Glad you're enjoying the sample!
