### ISSUE TITLE
Cannot make it work 'Join game'

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Windows-appsample-quizgame#5]
First of all I apologize might be is a silly thing I am doing wrong. I explain the test environment:

1.- Windows 10 desktop (10.0.586)
2.- Lumia 1320. (10.0.10586.107)
3.- Another Windows 10 desktop (10.0.14295)

I can ping from one to another and remote debugger also works. I have checked the firewall and the apps are allowed. On both 2 and 3 never get's activated the Join button.

Is there any advice to follow about what could be wrong? I do not see any exception and that's my first time trying to understand this matter about networking. Thank you.

**Comment by msatranjr** [comment]
There are a number of things that could cause this. The join button doesn’t become activated until the client has received a UDP multicast message (which should trigger the event handler in UdpParticipant.cs line 137) AND you start typing a name in the text box. Did you start typing a name in the text box?

Did you pull down the latest changes from master with the **privateNetworkClientServer** capability enabled in the client app?

Some LAN systems don’t allow UDP multicast packets to be sent/received, so you may want to consider checking with your network admin or router settings.

Let me know if it still doesn’t work after you’ve tried the above.
Thanks,
-Michael

**Comment by juanpaexpedite** [comment]
Well thank you for the answer it must be a networking discovery issue (yes really great implementation the DelegateCommand), cause I tried https://github.com/lidgren portable from nuget and also fails the discovery. I decided to use that library writing down the IP address in the client (that works), because in that way will always work. You can close the 'issue'.

**Comment by juanpaexpedite** [comment]
Well also I have just tried the StreamSocket example and works like a charm on both sides (mobile / desktop as server and client), I will create a library with that because it contains events, that is better than using the lidgren and I understand might be optimized.

**Comment by msatranjr** [comment]
Closing the issue per our discussion. Thanks for trying out the sample, I'm glad that the StreamSocket example works out for you.
